### ISSUE TITLE
Fatal error: eval()'d code: Can't use function return value in write context

### ISSUE THREAD

**Issue by pkarecki** [PrestaShop/dotpay#11]
Problem was reported by one of our merchants: 

``[PrestaShop] Fatal error in module file :/home/.../classes/module/Module.php(1238) : eval()'d code:
Can't use function return value in write context``

PrestaShop version 1.6.0.11

User reported that after this error, whole section "Modules" in BO does not work.

**Comment by pkarecki** [comment]
Fatal error: Can't use function return value in write context in /www/mamtwory_www/www/modules/dotpay/dotpay.php on line 236
[PrestaShop] Fatal error in module dotpay:
Can't use function return value in write context

**Comment by pkarecki** [comment]
Issue found: ```Note: Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In other words, the following will not work: empty(trim($name)). Instead, use trim($name) == false.```

**Comment by Quetzacoalt91** [comment]
Indeed, I did not see that in this compressed function.

You can post a PR to fix this issue. I'll merge it today if you do it on time. :)

**Comment by pkarecki** [comment]
Fixed in 1.4.0 :-)

Thanks!
